[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "16.6.2"
  YARN_VERSION = "1.22.15"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
package = "@netlify/plugin-gatsby"
