name: Generate Markdown File

# 毎月10日の0時0分に実行
on:
  schedule:
    - cron: '0 0 10 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref:
            main

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.6.2'
        cache: npm

    - name: Install dependencies
      run: npm install

    - name: Generate markdown file
      run: node ./src/libs/generateInformationMarkdown.js

    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Add generated markdown file"
        git push
